# Generated by Django 2.0.3 on 2018-09-14 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('phone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('designation', models.CharField(choices=[('Head of Department', 'Head of Department'), ('Manager', 'Manger'), ('Asst. Manager', 'Asst. Manager'), ('Executive', 'Executive'), ('Engineer', 'Engineer'), ('Sr.Engineer', 'Sr.Engineer'), ('Lead Engineer', 'Lead Engineer')], max_length=20)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='employee.Department')),
            ],
        ),
    ]
