# Generated by Django 2.0.3 on 2018-09-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_auto_20180919_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(choices=[('Head of Department', 'Head of Department'), ('Manager', 'Manger'), ('Asst. Manager', 'Asst. Manager'), ('Executive', 'Executive'), ('Engineer', 'Engineer'), ('Sr.Engineer', 'Sr.Engineer'), ('Lead Engineer', 'Lead Engineer')], max_length=20, null=True),
        ),
    ]
