# Generated by Django 2.0.3 on 2018-09-17 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0005_auto_20180914_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('assign_time', models.DateTimeField(auto_now_add=True)),
                ('complete_time', models.DateTimeField()),
                ('group_task', models.BooleanField(default=False)),
                ('assign_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_assign_by', to='employee.Employee')),
                ('assign_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_assign_to', to='employee.Employee')),
            ],
        ),
    ]
