# Generated by Django 2.0.3 on 2018-09-17 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Initial', 'Initial'), ('Half Done', 'Half Done'), ('Done', 'Done')], default='Initial', max_length=20),
        ),
    ]
