# Generated by Django 2.0.3 on 2018-09-17 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='complete_time',
            field=models.DateField(),
        ),
    ]
