# Generated by Django 2.0.3 on 2018-09-17 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_auto_20180914_2305'),
        ('task', '0004_auto_20180917_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=2000, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('announced_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announced_by', to='employee.Employee')),
                ('announced_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announced_to', to='employee.Employee')),
            ],
        ),
    ]
