# Generated by Django 2.0.3 on 2018-09-19 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_auto_20180919_1136'),
        ('task', '0005_announcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('topic', models.TextField(max_length=2000, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('schedule_time', models.DateTimeField(null=True)),
                ('schedule_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_by', to='employee.Employee')),
                ('schedule_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_to', to='employee.Employee')),
            ],
        ),
    ]
