# Generated by Django 2.0.3 on 2018-09-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_training'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='schedule_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
