# Generated by Django 2.0.3 on 2018-09-19 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_auto_20180919_1136'),
        ('task', '0007_auto_20180919_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=2000, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('meeting_time', models.DateTimeField(blank=True, null=True)),
                ('arranged_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arranged_by', to='employee.Employee')),
                ('arranged_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arranged_for', to='employee.Employee')),
            ],
        ),
    ]
